# Generated by Django 5.0 on 2024-01-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0006_alter_subject_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
