# Generated by Django 5.0 on 2024-01-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0022_studentresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='grade_mark',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='pratical_mark',
            field=models.IntegerField(default=0),
        ),
    ]
