# Generated by Django 5.0 on 2024-01-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0024_alter_studentresult_pratical_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='pratical_mark',
            field=models.IntegerField(default=0),
        ),
    ]
