# Generated by Django 5.0 on 2024-01-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0026_alter_studentresult_pratical_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='grace_mark',
            field=models.IntegerField(default=0),
        ),
    ]
