# Generated by Django 5.0 on 2024-01-14 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0028_alter_studentresult_grace_mark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentresult',
            old_name='pratical_mark',
            new_name='practical_mark',
        ),
    ]
