# Generated by Django 5.0 on 2024-01-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0030_studentresult_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='grade_mark',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='result',
            field=models.TextField(),
        ),
    ]
