# Generated by Django 5.0 on 2024-01-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0031_alter_studentresult_grade_mark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='grade_mark',
            field=models.TextField(default='None'),
        ),
    ]
