# Generated by Django 5.0 on 2024-01-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0035_alter_studentresult_assignment_mark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
