# Generated by Django 5.0 on 2024-01-14 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0037_alter_studentresult_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='result',
        ),
    ]
