# Generated by Django 5.0 on 2024-01-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0038_remove_studentresult_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mobile_no',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_mobile_no',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='study_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
