# Generated by Django 5.0 on 2024-01-14 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0040_alter_attendance_report_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='session_year_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.session_year'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.subject'),
        ),
    ]
