# Generated by Django 5.0 on 2024-01-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0041_alter_attendance_session_year_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='highest_education',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='staff',
            name='mobile_no',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staff',
            name='position',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'ADMIN'), (2, 'STAFF'), (3, 'STUDENT')], default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='salary',
            field=models.BigIntegerField(default=0),
        ),
    ]
